from sqlalchemy import Column, Integer, String, Text, JSON, TIMESTAMP
from database import Base


class SDO(Base):
    __tablename__ = "sdos"

    id = Column(Integer, primary_key=True)
    sdo_title = Column(String(255))
    sdo_fullname = Column(String(255))
    access_list = Column(Text)
    url = Column(String(255))
    currency_id = Column(Integer)
    sdo_shortdesc = Column(Text)
    sdo_detaildesc = Column(Text)
    sdo_banner = Column(String(255))
    sdo_uploadfile = Column(String(255))
    watermark = Column(Integer)
    status = Column(Integer)
    promote = Column(Integer)
    meta_title = Column(String(500))
    meta_keyword = Column(Text)
    meta_description = Column(Text)
    created_by = Column(Integer)
    updated_by = Column(Integer)
    created_at = Column(TIMESTAMP)
    updated_at = Column(TIMESTAMP)
    structure_data = Column(Text)
    free_structure_data = Column(Text)
    free_meta_title = Column(String(500))
    free_meta_description = Column(Text)
    BSBESales = Column(Integer)
    BSBInternal = Column(Integer)
    BSBSubscription = Column(Integer)
    DailyDownloadLimit = Column(Integer)
    sdo_shortdesc_detail = Column(Text)
    address0 = Column(String(50))
    address1 = Column(String(50))
    address2 = Column(String(50))
    address3 = Column(String(50))
    contact_name = Column(String(50))
    designation = Column(String(50))
    phone = Column(String(50))
    pincode = Column(String(50))
    email = Column(String(50))
    del_format_data = Column(Text)
    other_sdos = Column(JSON)